### ISSUE TITLE
Rack::QueryParser::InvalidParameterError: invalid %-encoding

### ISSUE THREAD

**Issue by yunixon** [erikdahlstrand/shrine-rails-example#17]
We get these errors:

```
ArgumentError: invalid %-encoding (cwAj48LEStGei5i+tR%YzQ.jpg)
Rack::QueryParser::InvalidParameterError: invalid %-encoding
```
/presign?filename=cwAj48LEStGei5i%20tR%25YzQ.jpg
/presign?filename=4TpA5aMGRMu%25AXwpAXDK2Q.jpg

rails 5.1.6
rack 2.0.5
shrine 2.12

**Comment by janko-m** [comment]
Thanks for the report. Can you show me the full stack trace?

**Comment by yunixon** [comment]
```
F, [2018-10-09T11:06:25.974859 #32406] FATAL -- : [32491523-8c8a-40ea-9375-9ceacecbf225] Rack::QueryParser::InvalidParameterError (invalid %-encoding (cwAj48LEStGei5i+tR%YzQ.jpg)):
F, [2018-10-09T11:06:25.974877 #32406] FATAL -- : [32491523-8c8a-40ea-9375-9ceacecbf225]
F, [2018-10-09T11:06:25.974907 #32406] FATAL -- : [32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/query_parser.rb:72:in `rescue in parse_nested_query'
[32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/query_parser.rb:60:in `parse_nested_query'
[32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/request.rb:468:in `parse_query'
[32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/request.rb:319:in `GET'
[32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/request.rb:358:in `params'
[32491523-8c8a-40ea-9375-9ceacecbf225] rack (2.0.5) lib/rack/request.rb:20:in `params'
[32491523-8c8a-40ea-9375-9ceacecbf225] shrine (2.12.0) lib/shrine/plugins/presign_endpoint.rb:200:in `get_presign_location'
[32491523-8c8a-40ea-9375-9ceacecbf225] shrine (2.12.0) lib/shrine/plugins/presign_endpoint.rb:185:in `handle_request'
[32491523-8c8a-40ea-9375-9ceacecbf225] shrine (2.12.0) lib/shrine/plugins/presign_endpoint.rb:172:in `block in call'
[32491523-8c8a-40ea-9375-9ceacecbf225] shrine (2.12.0) lib/shrine/plugins/presign_endpoint.rb:168:in `catch'
[32491523-8c8a-40ea-9375-9ceacecbf225] shrine (2.12.0) lib/shrine/plugins/presign_endpoint.rb:168:in `call'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[32491523-8c8a-40ea-9375-9ceacecbf225] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
```

**Comment by hmistry** [comment]
@yunixon Thanks for reporting the issue. I've submitted a PR with a fix pending approval/merge.
