### ISSUE TITLE
Another Module build failed

### ISSUE THREAD

**Issue by salex** [erikdahlstrand/shrine-rails-example#42]
Cloned the example to see what it would do.

I have node v14.10.1. Don't know much about how all this stuff works, but got the below error when running webpack-dev-server and have no idea  how to fix it. 

``` ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/salex/Work/rf/shrine-rails-example/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/salex/Work/rf/shrine-rails-example/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
```

**Comment by janko** [comment]
Thanks for reporting, I was able to reproduce the error. I've updated the packages, and that seems to have fixed the issue.
